# Generated by Django 3.1.7 on 2021-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0007_auto_20210502_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, default='NULL', max_length=250, null=True),
        ),
    ]
