# Generated by Django 3.1.7 on 2021-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0008_auto_20210528_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
