# Generated by Django 3.1.7 on 2021-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0009_auto_20210528_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaexperience',
            name='institute',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
