# Generated by Django 3.1.7 on 2021-05-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0010_auto_20210528_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaexperience',
            name='sector',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
