# Generated by Django 3.1.7 on 2021-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0012_education_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='result',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
